[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow",
    "validates_models: marks tests as one which validates service models",
]

[tool.isort]
profile = "black"
line_length = 79
honor_noqa = true
src_paths = ["botocore", "tests"]

[tool.ruff]
exclude = [
    ".bzr",
    ".changes", # from .pre-commit-config.yaml
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".github", # from .pre-commit-config.yaml
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "botocore/compat.py", # from .pre-commit-config.yaml
    "botocore/data", # from .pre-commit-config.yaml
    "botocore/vendored", # from .pre-commit-config.yaml
    "buck-out",
    "build",
    "dist",
    "docs/", # from .pre-commit-config.yaml
    "node_modules",
    "site-packages",
    "tests/functional/endpoint-rules", # from .pre-commit-config.yaml
    "tests/unit/auth/aws4_testsuite", # from .pre-commit-config.yaml
    "tests/unit/data/endpoints/", # from .pre-commit-config.yaml
    "tests/unit/response_parsing/xml", # from .pre-commit-config.yaml
    "venv",
]

# Format same as Black.
line-length = 79
indent-width = 4

target-version = "py38"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "UP"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings, spaces for indents
# and trailing commas.
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-format = false
docstring-code-line-length = "dynamic"
