#!/usr/bin/env python
# Don't run tests from the root repo dir.
# We want to ensure we're importing from the installed
# binary package not from the CWD.

import os
import argparse
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(os.path.join(REPO_ROOT, 'tests'))


def run(command):
    return check_call(command)


parser = argparse.ArgumentParser()
parser.add_argument('noseargs', nargs='*', default=['unit/', 'functional/'], help='BAR!')
parsed = parser.parse_args()

command = [
    'nosetests',
    '--with-coverage',
    '--cover-erase',
    '--cover-package',
    'botocore',
    '--with-xunit',
    '--cover-xml',
]
command += parsed.noseargs
run(command)