#!/usr/bin/env python
# Don't run tests from the root repo dir.
# We want to ensure we're importing from the installed
# binary package not from the CWD.

import os
import sys
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))


def main():
    os.chdir(os.path.join(REPO_ROOT, 'tests'))

    command = [
        'nosetests',
        '--with-coverage',
        '--cover-erase',
        '--cover-package', 'botocore',
        '--cover-xml',
        '--with-xunit',
        '-v',
    ]

    extra_args = sys.argv[1:]
    if extra_args:
        command.extend(extra_args)
    else:
        command.extend(['unit/', 'functional/'])

    return check_call(' '.join(command), shell=True)

if __name__ == '__main__':
    main()
