name: Closed Issue Message
on:
    issues:
       types: [closed]

permissions:
  contents: read

jobs:
    auto_comment:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
        - uses: aws-actions/closed-issue-message@0b50d3fb9d583aabd14e88ec0639b4f6e67d882f
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
                     This issue is now closed. Comments on closed issues are hard for our team to see.
                     If you need more assistance, please open a new issue that references this one.
